name: Build and Deploy Flutter Web

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Inject Custom App Code
        run: |
          cp main.dart /tmp/main.dart
          flutter create . --overwrite --project-name lcc_holding_tax_calculator
          cp /tmp/main.dart lib/main.dart

      - name: Build Web
        run: flutter build web --release --base-href "/lcc-holding-tax-calculator/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
